In [21]:
import numpy as np
import pandas as pd
import requests

In [ ]:
class CninfoAPI:
    def __init__(self, key="***REMOVED***", secret="***REMOVED***", is_testAPI=False) -> None:
        if is_testAPI:
            self.ACCESS_KEY = "***REMOVED***"
            self.ACCESS_SECRET = "***REMOVED***"
            self.BASE_URL = "http://webapitest.cninfo.com.cn"
        else:
            self.ACCESS_KEY = key
            self.ACCESS_SECRET = secret
            self.BASE_URL = "http://webapi.cninfo.com.cn"
        
        request_for_token = requests.post(self.BASE_URL + "/api-cloud-platform/oauth2/token", data={
            "grant_type": "client_credentials",
            "client_id": self.ACCESS_KEY,
            "client_secret": self.ACCESS_SECRET
        })
        if request_for_token.status_code == requests.codes.ok:
            res_dict = request_for_token.json()
            self.token = res_dict.get('access_token')
        else:
            self.token = ""


    def getStockSeq(self, scode="000001", sdate="2022-01-13", edate="2022-01-25"):
        STOCK_API = "/api/stock/p_stock2402"
        stock_req = requests.get(self.BASE_URL+STOCK_API, params={
            "scode": scode, 
            "sdate": sdate.replace("-", ""), 
            "edate": edate.replace("-", ""), 
            "access_token": self.token
        })
        print(stock_req.json())
        if stock_req.status_code == requests.codes.ok:
            records = stock_req.json().get('records')
        else:
            records = {
                "code": stock_req.json().get('resultcode'),
                "msg": "cninfo接口错误：" + stock_req.json().get('resultmsg')
            }
        
        return records


    def getIndexSeq(self, scode="000300", sdate="2022-01-13", edate="2022-01-25"):
        INDEX_API = "/api/index/p_index2905"
        index_req = requests.get(self.BASE_URL+INDEX_API, params={
            "scode": scode, 
            "sdate": sdate.replace("-", ""), 
            "edate": edate.replace("-", ""), 
            "access_token": self.token
        })

        if index_req.status_code == requests.codes.ok:
            records = index_req.json().get('records')
        else:
            records = {
                "code": index_req.json().get('resultcode'),
                "msg": "cninfo接口错误：" + index_req.json().get('resultmsg')
            }
        
        return records
        
    def getIndustry(self, scode="000001"):
        INDUSTRY_API = "/api/bigdata/p_chain_by_scode"
        industry_req = requests.get(self.BASE_URL+INDUSTRY_API, params={
            "scode": scode, 
            "access_token": self.token
        })

        if industry_req.status_code == requests.codes.ok:
            records = industry_req.json().get('records')
        else:
            records = {
                "code": industry_req.json().get('resultcode'),
                "msg": "cninfo接口错误：" + industry_req.json().get('resultmsg')
            }
        
        return records

In [ ]:
stockCode = '000001'
api = CninfoAPI(is_testAPI=True)
industries = api.getIndustry(stockCode)

In [ ]:
industries

In [28]:
industries_df = pd.read_csv("/home/chenhaoran/FinancialTextAnalysis/industries_df.txt", dtype={'COMPANY_CODE': str}, index_col=[0])
industries_df

,UDINDUSTRYNAME,POSITION,CODE,UDINDUSTRYCODE,INDUSTRYCODE,INDUSTRYNAME,NAME,COMPANY_CODE
0,物联网服务,上游,fh009382,I020206,I02020614,智慧工厂,智慧工厂,300316
1,路由器,上游,fh009382,I02010201,I02020614,智慧工厂,智慧工厂,300316
2,大数据技术,上游,fh009382,H020401,I02020614,智慧工厂,智慧工厂,300316
3,自动化检测设备,上游,fh009382,C01081401,I02020614,智慧工厂,智慧工厂,300316
4,计算机网络系统集成,上游,fh009382,H02070103,I02020614,智慧工厂,智慧工厂,300316
...,...,...,...,...,...,...,...,...
148,钙,上游,lsx033n048,B020424,E020143,食品添加剂,护色剂,002568
149,海藻酸钠,上游,lsx033n048,B02050505,E020143,食品添加剂,护色剂,002568
150,左旋肉碱,上游,lsx033n048,E02013108,E020143,食品添加剂,护色剂,002568
151,食品综合,下游,lsx033n048,E0205,E020143,食品添加剂,护色剂,002568
152,其他饮料,下游,lsx033n048,E020609,E020143,食品添加剂,护色剂,002568

In [23]:
node_dict = dict()
counter = 0
for industry in industries_df.INDUSTRYNAME:
    if node_dict.get(industry) != None:
        # print("seen", industry, counter)
        continue
    else:
        node_dict[industry] = counter
        print(industry, counter)
        counter += 1
print(len(node_dict), counter)
for udindustry in industries_df.UDINDUSTRYNAME:
    if node_dict.get(udindustry) != None:
        continue
    else:
        node_dict[udindustry] = counter
        counter += 1
print(len(node_dict), counter)

智慧工厂 0
机电设备安装劳务 1
橡胶加工设备 2
扩散炉 3
单晶炉 4
气动密封 5
智能能源 6
晶圆 7
多晶炉 8
自动化工程 9
电池片生产设备 10
三极管 11
LED衬底材料 12
新能源乘用车 13
乘用车 14
货车 15
SUV 16
MPV 17
轿车 18
休闲汽车 19
模具 20
加工劳务 21
道路运输 22
工程总承包（EPC） 23
水利工程 24
放射性金属矿石 25
电力设计 26
电力工程施工 27
机电工程 28
房地产开发 29
水力发电 30
工程勘察设计 31
水电机组及相关设备 32
股份制银行 33
信用贷款 34
跨境支付 35
消费金融 36
区块链金融 37
中小微企业贷 38
信用卡 39
供应链金融 40
直销银行 41
信贷 42
企业金融 43
传统仓储 44
度假型公寓 45
办公楼 46
养老地产 47
住宅租赁 48
nan 49
体育地产 50
园区物业管理 51
商场开发 52
普通住宅 53
人才安居房 54
物流地产 55
居住物业管理 56
商业物业管理 57
办公用房建筑工程 58
建筑防水工程 59
第三方工程评估 60
物业管理 61
军用声纳 62
网络安全 63
服务器 64
开关电源 65
安全集成 66
信息加密/身份认证 67
通信电源 68
液晶电视（含CCFL及LED电视） 69
电源 70
打印机及其零部件 71
台式电脑 72
一体机 73
导弹防御系统 74
电子对抗系统 75
LED液晶显示器 76
网络安全设备 77
协同管理软件 78
计量检测 79
信息技术 80
信息安全 81
涤纶加弹丝 82
涤纶纤维(聚酯纤维) 83
涤纶牵伸丝 84
化学纤维 85
石化服务 86
热电、供暖 87
智能制造 88
一次电池 89
氢燃料电池 90
石墨烯及其制品 91
消费电池 92
锂电结构件 93
电池 94
锂电池 95
电池模组及电池系统 96
电表 97
自动光学检测设备AOI 98
锰酸锂 99
磷酸铁锂 100
三元材料 101
磷酸铁锂电池 102
三元锂电池 103
储能设备 104
电子元器件 105
生产平台设备 106
油气设备 107
钻井平台设备 108
作业船 109
船舶制造 110
船舶维护服务 111
航空母舰 112
驱逐舰 113
海军装备 114
护卫舰 115
补给舰 116
船舶贸易 117
工业 118
商务服务 119
吸附破伤风疫苗 120
脊髓灰质炎减毒活疫苗 121
麻腮风联合减毒活疫苗 122
脑膜炎疫苗 123
重组乙型肝炎疫苗 124
血制品 125
人血白蛋白 126
静注人免疫球蛋白 127
破伤风人免疫球蛋白 128
狂犬病人免疫球蛋白 129
麻疹疫苗 130
无细胞百白破联合疫苗 131
吸附白喉破伤风联合疫苗 132
水痘减毒活疫苗 133
三价流感疫苗 134
重组人干扰素α 135
人纤维蛋白原 136
骨科外用贴膏剂 137
二氧化硅（白炭黑） 138
中药材种植 139
骨骼与肌肉用药 140
蒲地蓝制剂 141
健胃消食片 142
洗发护发用品 143
中药配方颗粒 144
三七 145
中药饮片 146
医药批发 147
生物治疗技术 148
种植业 149
旅游酒店餐饮 150
白酒 151
酒类 152
智能家居系统方案解决商 153
液晶显示器背光源 154
WiFi模组 155
钟表 156
电子设备及服务 157
电子制造服务 158
消费类电子加工服务 159
触控笔 160
消费电子功能性器件 161
电子元件加工服务 162
整流器 163
数字信号拓展坞 164
MEMS麦克风 165
封装和测试 166
智能手表 167
无线通信设备 168
消费电子零售 169
销售点情报管理系统（POS机） 170
计算机零部件 171
汽车电子系统 172
独立光伏发电 173
并网光伏发电 174
光伏电站 175
太阳能电池组件 176
太阳能电池片 177
分布式光伏发电 178
太阳能电池板零部件 179
LED封装产品 180
光伏玻璃 181
传统能源 182
汽车外贸 183
智能驾驶 184
新能源汽车 185
智能电动车 186
智能汽车 187
汽车经销 188
新能源汽车零部件 189
汽车金融 190
轮胎平衡块 191
路基工程 192
工程设计 193
港口工程 194
导航终端 195
桥梁工程 196
城市轨道交通工程 197
医药研发外包服务（CRO） 198
临床CRO 199
SMO服务 200
药物发现服务 201
临床前CRO 202
钼矿石 203
钴矿石 204
稀有轻金属矿 205
稀有难熔金属矿 206
钨矿石 207
钴盐 208
靶材金属原料 209
资源再生利用 210
有色金属贸易 211
矿山工程 212
养生壶 213
烤箱 214
无线智能家居套装 215
家用中央空调 216
吸尘器 217
综合电器零售 218
波轮洗衣机 219
分筒洗衣机 220
热泵干衣机 221
分体式空调 222
移动空调 223
燃气壁挂炉 224
空气源热泵 225
电吹风 226
挂烫机、熨斗 227
电风扇 228
电饭煲 229
电磁炉 230
抽油烟机 231
电热水壶 232
电压力锅 233
微波炉 234
电烤炉 235
饮水机 236
面包机 237
料理机 238
AI家居 239
智能烟雾探测器 240
智能冰箱 241
智能空调 242
智能空气净化器 243
智能门锁 244
空调 245
燃气热水器 246
智能洗衣机 247
厨房电器 248
新风系统 249
空气净化器 250
集成灶 251
家居电器 252
换热器 253
个人护理器具 254
冰箱 255
洗衣机 256
扫地机器人 257
浴霸 258
电热水器 259
工商用清洁除尘设备 260
空气过滤器 261
取暖器 262
空调安装劳务 263
电源插头 264
加湿器 265
滚筒洗衣机 266
智能家居 267
健康咨询 268
工业机器人系统集成 269
热水器 270
白色家电批发 271
物联网服务 272
家庭用品批发 273
家具制造设备 274
结构钢 275
建筑用钢 276
扁钢 277
圆钢 278
稀土金属矿石 279
铁轨 280
精矿 281
普通钢 282
铁精矿 283
矿石冶炼 284
工业园区开发 285
商铺租赁 286
智能音箱 287
无线充电设备 288
家电类智能家居 289
家用净水器 290
直销渠道 291
铁路工程 292
道路桥梁工程 293
房屋建筑工程 294
架桥机 295
盾构设备 296
路面工程 297
交通领域工程规划 298
铺轨机 299
制药用净化、清洗与消毒、灭菌设备 300
工程监理 301
地铁（城市轨道交通设备） 302
基础设施服务（IaaS） 303
城市建设投资（城投） 304
公路工程 305
有轨电车零部件及配件制造 306
工程勘察 307
房地产租赁 308
铁路货运 309
综合类证券公司 310
证券承销 311
证券经纪 312
证券投资财务顾问 313
证券资产管理 314
互联网券商 315
金融期货 316
证券自营 317
证券投资咨询 318
资产证券化 319
财富管理 320
融资租赁 321
商品期货 322
投资银行业务 323
太阳能EVA胶膜 324
太阳能焊带 325
太阳能接线盒 326
焊带 327
热熔胶膜 328
过程工艺控制设备 329
面板检测设备 330
半导体测试设备ATE 331
干膜 332
封装材料 333
电子材料 334
功能性材料 335
光伏发电 336
办公用品 337
绘画材料零售 338
办公设备 339
办公耗材 340
书写纸 341
B2C类综合电商 342
办公文具 343
零售业 344
信息技术数据处理 345
信息技术数据服务 346
四氧化三钴 347
钴镍废料 348
手抓矿、尾矿 349
钴精矿 350
钴 351
贵金属回收利用 352
氢氧化钴 353
电积铜 354
锂离子电池正极材料 355
硫酸钴 356
三元前驱体 357
镍制品 358
资源回收 359
铜粉、铜合金粉 360
钴酸锂 361
电池回收 362
有色金属材料 363
啤酒 364
鸡尾酒 365
民航客运 366
行李服务 367
航空航天产品与服务 368
航空运输 369
航空服务 370
交叉型乘用车 371
平视显示器（HUD） 372
能源 373
电子控制设备 374
汽车租赁 375
BMS电池管理系统 376
汽车 377
金融 378
混凝土搅拌站 379
混凝土泵车 380
土壤修复工程设备 381
抓料机 382
现拌混凝土（普通混凝土） 383
装备与自动化 384
发电机组及相关设备 385
挖掘机 386
平地机 387
压实机 388
港口机械 389
消费电子制造设备 390
工程起重机 391
沥青混凝土路面施工机械 392
混凝土预制构件生产设备（PC构件生产设备） 393
升降电梯 394
基建设施农业设备 395
工业机械技术服务 396
混凝土机械 397
移动式工程起重机 398
固定式工程起重机 399
中型挖掘机 400
大型挖掘机 401
广义小型挖掘机 402
混凝土搅拌车 403
混凝土泵 404
小型装载机 405
包装机械 406
铲运机械 407
旋挖钻机 408
水平定向钻机 409
工程机械 410
离子交换膜（荷电膜） 411
活性染料 412
染料中间体 413
农药中间体 414
还原染料 415
酸性染料 416
染料 417
硫酸铵 418
丁基橡胶 419
分散染料 420
特种橡胶 421
甲苯二异氰酸酯（TDI） 422
互联网出行 423
直接染料 424
硫化染料 425
双酚S 426
汽车安全带 427
基础化工 428
工业服务 429
风力发电 430
电力行业软件 431
垂直风力发电 432
风电机组及相关设备 433
风机叶片 434
风机及其零部件 435
金融业大数据 436
金融数据信息服务 437
智能投顾 438
区块链记录保全 439
金融交易软件 440
金融IT系统 441
证券行情交易系统 442
电网调度自动化 443
配网自动化 444
火电厂自动化 445
水电站自动化 446
输电 447
配电 448
电力自动化设备 449
特高压直流控制保护 450
换流变压器 451
特高压变压器 452
电力生产系统集成 453
断路器 454
绝缘防护工具 455
变电站自动化 456
工业交换机 457
输配电设备部件 458
开发者服务 459
IT支持服务 460
换流阀 461
安防设备 462
充电服务 463
换电设备 464
充电设备 465
电气设备 466
企业融资 467
证券 468
信托 469
基金 470
连锁药店 471
DTP、DTC药房 472
医药流通 473
医药代理服务 474
医药零售 475
液压泵 476
高空作业车 477
高空作业机械 478
自行走式高空作业平台 479
移动式高空作业平台 480
固定式高空作业平台 481
核燃料 482
核电机组及相关设备 483
沸水堆核电站 484
压水堆核电站 485
重水堆核电站 486
超滤膜 487
丙烯酸 488
PU树脂 489
PMMA树脂 490
阻燃PC薄膜 491
丙烯酸胶粘剂 492
合成氨 493
焦炉煤气 494
醇酸树脂 495
高吸水树脂（SAP） 496
热塑性聚氨酯弹性体(TPU) 497
建筑保温工程 498
二苯基甲烷二异氰酸酯（纯MDI） 499
二苯基甲烷二异氰酸酯（聚合MDI） 500
乙烯 501
丁二醇 502
聚醚 503
盐酸 504
丙烷 505
生物发酵工业 506
氯酸钠 507
纯碱 508
溶剂 509
氢气 510
聚氨酯扩链剂 511
过氧化氢 512
环氧丙烷 513
黄磷 514
科研试剂（特种化学品） 515
氯化亚砜 516
聚氨酯 517
度假村 518
配饰 519
珠宝首饰 520
旅游资源运营管理 521
珠宝首饰零售 522
食品饮料烟草 523
餐饮服务 524
日用化妆品 525
医疗健康保健 526
景区经营管理 527
企业票据金融 528
AI金融 529
场景金融 530
区块链 531
其他金融 532
期货投资咨询 533
期货经纪综合 534
体外循环及血液净化耗材 535
血液灌流器 536
免疫吸附耗材 537
血液透析中心 538
辅助医疗设备 539
MCU芯片 540
DRAM 541
NAND Flash 542
传感器芯片 543
NOR Flash 544
存储芯片 545
智能传感器 546
集成电路设计 547
智能控制器 548
集成电路 549
化学发光仪 550
化学发光试剂 551
肿瘤标志物POCT 552
体外诊断 553
传染病类即时检测设备及耗材 554
酶联免疫IVD 555
医药精细化学品 556
免疫生化诊断 557
即时检测设备 558
实时荧光定量PCR（qPCR） 559
分子诊断 560
甲状腺激素及抗甲状腺药 561
医学诊断服务外包 562
人工智能通用技术层 563
人工智能通用应用层 564
智能语音 565
电子卡类 566
TOF镜头 567
生物识别 568
机器视觉 569
其他软件服务 570
传感器设计 571
指纹识别传感器 572
指纹识别解决方案 573
光学式指纹识别解决方案 574
电容式指纹识别解决方案 575
超声波式指纹识别解决方案 576
智能玩具技术 577
集成电路制造 578
EGFR靶点药物 579
恩沙替尼 580
埃克替尼 581
单克隆抗体 582
小分子靶向药物 583
抗肿瘤及免疫调节制剂 584
伏立诺他 585
抗肝癌靶点及靶向药 586
埃替拉韦 587
抗肺癌靶点及靶向药 588
城市商业银行 589
养老金融与保险 590
角膜塑形镜 591
隐形眼镜 592
眼镜 593
眼科治疗器械 594
智能交互 595
板卡 596
在线学前教育平台 597
智慧校园类 598
智能互动教育设备 599
智能投影仪 600
LED显示控制系统 601
显示器 602
金融理财服务 603
百白破-Hib（四联苗） 604
百白破-脊灰-Hib（五联苗） 605
一类疫苗 606
二类疫苗 607
多价轮状病毒疫苗 608
HSA融合蛋白 609
13/23价肺炎球菌疫苗 610
融合通信技术 611
人用狂犬病疫苗 612
麻腮风-水痘（四联苗） 613
霍乱疫苗 614
抗乙肝病毒制剂 615
安宫牛黄丸 616
妇科用药 617
医药合同销售组织（CSO） 618
妇科中成药 619
中成药 620
中医养生 621
小檗碱 622
中医馆 623
乌鸡白凤丸 624
家用电器加工服务 625
流体电磁阀 626
电子废物拆解回收 627
制冷设备及部件 628
专用性空调 629
除湿机 630
废弃资源回收利用 631
永磁同步电机 632
重组蛋白 633
生物制药 634
信息技术服务 635
婚宴酒席 636
保健酒 637
酒水饮料餐饮服务 638
蒸馏酒 639
空调阀件 640
调节阀/控制阀 641
汽车热管理系统 642
汽车清洗泵 643
回转式压缩机 644
变频器 645
通用设备 646
固定无线接入设备 647
智能摄像机 648
移动通信设备 649
通信设备 650
视频会议终端 651
锂电池涂布机 652
锂电池真空搅拌机 653
锂电池分条机 654
中间相炭微球 655
钛酸锂 656
锂离子电池负极材料 657
负极包覆材料 658
涂布模头 659
石墨 660
金属基复合材料 661
锂电池专用生产设备 662
旅游地产 663
房地产销售 664
智慧消防 665
智能安防 666
深度摄像头 667
早教陪护机器人 668
人工智能芯片（AI芯片） 669
模式识别 670
AI安防 671
智能摄像头 672
智能交通硬件 673
视频监控设备 674
出入口控制设备 675
智能交通系统（ITS） 676
消防机器人 677
智慧城市 678
大数据技术 679
行业应用软件 680
商业服务机器人 681
半导体存储器 682
相机 683
智能硬件研发 684
油品运输 685
己二酸 686
氨纶 687
环己酮 688
仓储 689
生猪饲养 690
生猪屠宰加工 691
肉禽屠宰及加工 692
饲料 693
禽类饲料 694
养鸡业 695
肉制品 696
饲料产品 697
添加剂预混料 698
水产饲料 699
猪饲料 700
智慧农业 701
养鸭业 702
畜牧养殖业 703
食品 704
煤泥 705
无烟煤 706
褐煤 707
兰炭 708
煤制液体燃料 709
炼焦煤 710
动力煤 711
喷吹煤 712
原煤开采洗选 713
港口服务 714
氯乙烯 715
火力发电 716
煤炭深加工、炼焦、焦化 717
水路货运 718
高频高速印刷电路板 719
多层电路板 720
印刷电路板（PCB） 721
单层电路板 722
印制电路板装配制造（PCBA） 723
高密度互连板（HDI） 724
封装基板 725
刚性印刷电路板（RPCB） 726
外汇交易 727
行车记录仪 728
互联网增值服务 729
大数据安全 730
杀毒软件 731
移动广告平台 732
eMTC基站 733
垂直行业平台DMP 734
智能服饰 735
手机 736
物联网安全 737
线上网络广告 738
连接控制设备 739
游戏开发商 740
安全管理平台（SOC） 741
医疗行业大数据 742
CMO、CDMO 743
制剂工艺研究CMC 744
PD-1、L1靶点抑制剂 745
化学合成服务 746
临床前研究服务 747
药效学评价 748
药物安全性评价 749
I-III期临床研究服务 750
药物分子砌块生产 751
液体活检 752
左旋肉碱 753
婴儿CPAP系统 754
出凝血检测 755
医疗器械安装劳务 756
自动体外除颤器（AED） 757
医用呼吸机 758
医疗监护仪 759
医用超声诊断设备 760
常规一体式监护仪 761
心电图机 762
保健用品 763
核磁共振仪 764
电子功能性器件(绝缘纸、保护膜、胶带等) 765
家用呼吸机 766
生命支持类监测耗材 767
IVD流通 768
直接数字化X射线摄影系统（DR） 769
D型超声成像诊断仪 770
便捷式超声诊断仪 771
生化分析仪 772
自动检验流水线 773
流式细胞仪 774
流式细胞试剂 775
尿液诊断设备 776
药物基因组学 777
糖化血红蛋白仪 778
智能心电仪 779
医疗信息化 780
免疫诊断设备 781
内窥镜 782
生命支持设备 783
除颤仪 784
医学影像用耗材 785
医院后勤外包 786
手术灯 787
专科型超声诊断仪 788
康复诊断与评定器械 789
医疗器械 790
第三方责任险 791
车险 792
人寿保险 793
健康保险 794
保险公估 795
保险经纪 796
综合保险 797
企业保险 798
旅游保险 799
牙科保险 800
无人机保险 801
保险大数据 802
健康管理 803
养生服务 804
人身保险 805
国有银行 806
票据贴现 807
第三方保管服务 808
商业银行 809
砂浆 810
隔音产品 811
石膏板 812
新型墙体材料 813
互联网家装 814
新型建筑材料 815
煤矸石 816
防水卷材 817
门窗 818
石膏墙体材料 819
建筑轻钢结构 820
塑料型材 821
建材批发 822
氮化镓（GaN） 823
半导体 824
激光切割机 825
激光焊接机 826
激光打标机 827
锂电池卷绕机 828
锂电封口及清洗设备 829
入壳焊接设备 830
激光清洗机 831
激光熔覆机 832
光源、激光器 833
激光扫描器 834
光纤激光器 835
固体激光器 836
红宝石激光器 837
全液压岩心钻机 838
振镜 839
数字光处理（DLP） 840
选择性激光熔化（SLM） 841
细胞绘图打印（CBP） 842
牙科3D打印装备 843
激光雷达 844
划片机 845
谐波减速器 846
有线电视光纤传输设备 847
激光雕刻机 848
激光调阻机 849
激光毛化设备 850
激光照明设备 851
激光治疗设备 852
切割设备 853
专用设备 854
贝伐珠单抗 855
人免疫球蛋白 856
人凝血酶原复合物 857
太阳能生产设备 858
贝伐单抗 859
干化学IVD 860
医用高值耗材 861
疫苗 862
财务顾问（FA） 863
私募证券投资 864
甲醇 865
聚1-丁烯 866
5G射频芯片 867
射频开关 868
军用芯片 869
射频器件 870
卫星通信服务 871
卫星配套地面设备建设 872
广播电台 873
证券业 874
公募基金 875
电力公用事业 876
IC卡 877
手机快速充电芯片 878
逻辑芯片 879
DRAM存储器 880
进口煤炭 881
烟煤 882
煤炭贸易 883
煤炭开采工程 884
煤制气(水煤气) 885
采矿机械设备 886
大数据交易平台 887
交通运输服务 888
氯氮平 889
毒麻精药品配送 890
人尿激肽原酶（尤瑞克林） 891
抗细菌药-头孢类制剂 892
电子处方 893
华法林 894
医疗器械流通 895
智慧医疗 896
CD20靶点药物 897
HER2靶点药物 898
氟西汀 899
互联网医药营销 900
集装箱运输 901
装卸业务 902
HPV疫苗 903
微卡疫苗 904
Hib疫苗 905
AC-Hib（三联苗） 906
新型冠状病毒疫苗 907
卡介苗 908
运动控制器 909
伺服驱动器 910
通用运动控制（GMC） 911
电机 912
工厂自动化零部件 913
电梯控制系统 914
运动控制类工业自动化 915
工业互联网软件 916
伺服系统 917
伺服电机 918
编码器 919
水平多关节机器人（SCARA） 920
空调电机 921
人机界面（HMI） 922
低压变频器 923
反馈类工控自动化 924
牵引系统 925
电子继电器 926
汽车电控系统 927
新能源汽车电机 928
新能源汽车电机控制器 929
高低压设备 930
数字控制系统（CNC） 931
玻璃纤维布 932
电子级硅微粉 933
硅材料 934
铜球 935
覆铜箔板 936
柔性印刷电路板（FPC） 937
高频通信材料 938
高频覆铜板 939
铜箔 940
电子制程 941
移动通信天线 942
移动电源 943
手机周边产品 944
耳机 945
医用几丁糖 946
透明质酸（玻尿酸） 947
肉毒杆菌毒素 948
护肤品 949
办公和管理软件 950
字体软件 951
视频剪辑软件 952
文档服务 953
通用工具软件 954
担保贷款 955
铁路客运 956
票务系统 957
轨道交通运营维护 958
铁路轨道板 959
高铁客运 960
智能硬件 961
二极管 962
功率半导体 963
分立器件 964
场效应晶体管 965
地面运输服务 966
航班起降服务 967
机场建设工程施工 968
通用机场建设 969
运输机场建设 970
临时起降点建设 971
航天航空及国防 972
航空航天及国防 973
铝型材 974
粉煤 975
阳极炭块 976
铝矿石 977
超硬材料 978
铝合金 979
氢氧化铝 980
铝 981
心脑血管用药 982
民营综合医疗 983
医院管理 984
O2O医药电商 985
肿瘤专科医疗 986
儿童医院 987
干细胞增殖及制剂研发 988
CAR-T、TCR-T 989
全人源单抗 990
CDKs靶点药物 991
利拉鲁肽 992
曲妥珠单抗 993
VEGF靶点药物 994
生化诊断设备 995
阿莫西林 996
克林霉素 997
异烟肼 998
医疗服务外包 999
乙酸 1000
化肥 1001
三聚氰胺 1002
乙二酸（草酸） 1003
醋酐 1004
三甲胺 1005
甲醛 1006
二甲胺 1007
苯酚 1008
乙二醇 1009
黄金/金锭 1010
金矿石及其精矿 1011
铁矿石 1012
贵金属矿石 1013
重金属材料 1014
铜杆 1015
铟锭 1016
冶金工程 1017
铜 1018
铜精矿 1019
锌 1020
电解铜、阴极铜 1021
银矿石及其精矿 1022
燃料油 1023
石脑油 1024
原油贸易 1025
天然气运输 1026
LNG接收站 1027
涤纶预取向丝 1028
聚酯瓶片（PET瓶片） 1029
石化安全技术服务 1030
聚乳酸（PLA） 1031
塑料薄膜 1032
再生胶 1033
合成橡胶 1034
精对苯二甲酸（PTA） 1035
芳香烃 1036
PET切片 1037
汽油 1038
PE薄膜 1039
光电池 1040
光伏焊带制造设备 1041
门冬胰岛素 1042
胰岛素 1043
重组人胰岛素 1044
企业级网络设备 1045
智能耳机 1046
信号适配器/转换器 1047
有线充电器 1048
B2C家居家具电商 1049
外贸电子商务 1050
充储电产品 1051
消费电子批发 1052
医用敷料 1053
医用口罩 1054
家庭医疗器械 1055
医用卫生材料及敷料 1056
无纺布 1057
非织造布 1058
棉柔巾 1059
湿巾 1060
医用低值耗材 1061
家庭用品 1062
医用一次性无纺布 1063
棕榈油 1064
面条（挂面） 1065
豆粕 1066
农副产品加工业 1067
资本市场信用服务 1068
海外资产投资 1069
种猪培育 1070
猪用疫苗 1071
牧草种植 1072
浓缩饲料 1073
饲料原料 1074
动物保健（兽药） 1075
先心病封堵器 1076
心血管介入器械 1077
养老医疗保健 1078
智能体温计 1079
区域医疗卫生信息化 1080
降血脂用药 1081
康复辅助器具 1082
吻合器 1083
记忆形状合金 1084
尼美舒利 1085
医疗保健服务 1086
病房护理设备 1087
数字减影血管造影X线机（DSA） 1088
标测导管 1089
消融导管 1090
金属裸支架 1091
载药支架 1092
球囊扩张压力泵 1093
甘精胰岛素 1094
互联网慢病管理 1095
阿托伐他汀 1096
氯吡格雷 1097
阿哌沙班 1098
溶瘤病毒 1099
GLP-1受体激动剂 1100
球囊导管 1101
医疗保健 1102
知识流程外包（KPO） 1103
高净值理财服务 1104
信息系统集成服务 1105
信息技术外包（ITO） 1106
数据库（SQL）技术 1107
政务大数据 1108
IDC数据中心服务 1109
信息技术综合 1110
客户关系管理（CRM） 1111
车联网 1112
企业资源计划（ERP） 1113
公有云 1114
数据存储 1115
智能包装 1116
服务外包 1117
镍氢蓄电池 1118
复合调味料 1119
酱油 1120
味精 1121
调味品 1122
民航货运 1123
国际快递 1124
同城快递 1125
车货匹配 1126
物流调度 1127
冷库仓储 1128
综合物流 1129
钢绞线 1130
智慧物流 1131
AI物流 1132
跨境电商 1133
物流 1134
供应链服务企业 1135
物流无人机 1136
冷链物流 1137
物流金融 1138
大数据 1139
自动化物流装备 1140
背胶袋/快递袋 1141
甲苯 1142
矿藏勘探 1143
天然气及可燃冰勘探开采 1144
煤油 1145
石油炼制工艺(催化、裂化、蒸馏、焦化等) 1146
溶剂油 1147
变压器油 1148
石油与天然气勘测技术服务 1149
液化天然气 1150
气田技术服务 1151
丁苯橡胶 1152
润滑油基础油 1153
油气管网建设 1154
油气储运基地建设 1155
加油站 1156
石油天然气销售 1157
塑料包装材料 1158
综合性石油天然气企业 1159
管道铺设工程 1160
化学工程 1161
炼油专用设备 1162
原油勘探开采 1163
企业资产管理 1164
整流桥 1165
硅片 1166
单晶硅 1167
半导体设备 1168
饲料原料经销商 1169
全价配合饲料 1170
数字货币交易平台 1171
畜禽养殖 1172
工程塑料 1173
降解地膜 1174
树脂基复合材料 1175
改性塑料 1176
木塑复合材料 1177
碳纤维 1178
聚烯烃类 1179
抗氧化剂 1180
复合材料 1181
锦纶 1182
聚乙烯 1183
5G相控阵天线罩及其零部件 1184
前沿新材料 1185
交换机 1186
网络切片技术 1187
信息通信技术（ICT） 1188
三维扫描仪 1189
入侵防御IPS 1190
智能材料 1191
信息技术咨询 1192
研发设计软件 1193
3D扫描仪 1194
智慧政务 1195
光芯片 1196
小基站 1197
致冷芯片 1198
片仔癀 1199
抗肝炎中成药 1200
保健食品 1201
妇科炎症药 1202
皮肤科抗感染药 1203
中药 1204
民用飞机 1205
超级市场 1206
AI零售 1207
母婴用品零售 1208
图书出版 1209
智能零售 1210
衍生品零售 1211
零售科技 1212
自动售货机 1213
综合百货 1214
小程序软件 1215
互联网保险 1216
客户端游戏 1217
VR行业应用 1218
移动类游戏 1219
数字内容应用服务 1220
H5游戏 1221
配音及配乐 1222
游戏IP运营 1223
游戏发行及运营 1224
充电桩 1225
液晶显示模块LCM 1226
公共电汽车 1227
汽车电动机 1228
电动平衡重乘驾式叉车 1229
连接器零组件 1230
玻璃防护屏 1231
双离合变速器 1232
电池管理系统 1233
储能电池 1234
CMOS图像传感器 1235
彩色滤光片 1236
键盘 1237
手机代工 1238
背光模组 1239
锂离子电芯 1240
无轨电车整车 1241
电池模组 1242
光学镜头 1243
新能源客车 1244
CCD图像传感器 1245
手机结构件 1246
绝缘栅双极型晶体管（IGBT） 1247
交通运输 1248
电子设备与仪器 1249
精密注塑零部件 1250
精密注塑模具 1251
游戏运营服务 1252
游戏衍生服务 1253
汽车零部件 1254
工程金融 1255
职业技能培训 1256
职业资格培训 1257
公职类招录考试培训 1258
考研辅导机构 1259
教育培训 1260
美术培训 1261
互联网知识付费 1262
艺考培训 1263
教育行业类SaaS 1264
学前教育 1265
钛白粉 1266
硫酸 1267
钛铁矿 1268
锆 1269
化学原料药 1270
液压破碎设备 1271
工程机械配件 1272
铸件 1273
液压油缸 1274
液压控制系统 1275
液压密封 1276
履带密封 1277
液压柱塞泵 1278
液压阀 1279
电视节目制作 1280
游戏机 1281
电视游戏 1282
电竞培训 1283
体育IP产业 1284
电视剧发行 1285
社交游戏 1286
动漫 1287
影视 1288
逆变器 1289
太阳能集热 1290
光伏逆变器 1291
变流器 1292
智能微网 1293
视频会议服务 1294
专网无线通信 1295
核心网 1296
5G基带芯片 1297
5G基站 1298
大规模天线技术 1299
5G核心网 1300
无线CPE 1301
应用商店软件 1302
接入网 1303
网络优化服务 1304
微波传输设备 1305
定位芯片 1306
数字电视支付 1307
有线通信设备 1308
网络维护服务 1309
路由器 1310
射频芯片 1311
NB-IoT 1312
卫星通信设备 1313
刀片式服务器 1314
计算机网络系统集成 1315
软件定义通信(SDN) 1316
WDM、DWDM波分复用解复用器 1317
手机品牌商 1318
电子产品贸易 1319
商务类租赁 1320
游乐场 1321
文化旅游 1322
景区策划规划 1323
旅游服务 1324
固体废弃物处理 1325
环卫车 1326
核电用钢 1327
AI农业 1328
车架 1329
带电作业车 1330
车桥 1331
新型农业 1332
眼科专科医疗 1333
专科医疗 1334
远程医疗 1335
医学配镜 1336
眼科使用耗材 1337
医疗咨询 1338
智能网联汽车 1339
汽车精密注塑件 1340
电瓶车整车 1341
行星齿轮 1342
客车 1343
OLED显示器 1344
LCD显示器 1345
LED液晶显示屏 1346
手机零售 1347
内容电商 1348
车载影音娱乐系统 1349
LCD液晶显示屏 1350
显示器件 1351
智慧民生 1352
传感器 1353
硅橡胶 1354
六氟磷酸锂 1355
电解质 1356
锂离子电池电解液 1357
有机化工原料 1358
超硬刀具 1359
碳酸锂 1360
电解液添加剂 1361
二次电池 1362
电池材料 1363
售电 1364
鸦胆子油乳注射液 1365
头孢硫脒 1366
感冒类中成药 1367
清热解毒类中成药 1368
植物蛋白饮料 1369
保健药品 1370
板蓝根制剂 1371
头孢呋辛 1372
电子商务 1373
加盟服务 1374
咨询与调查 1375
医药及医疗器材零售 1376
原料药出口 1377
医疗检测服务 1378
品牌管理服务 1379
促销品服务 1380
卡丁车 1381
摩托车 1382
雪地车 1383
玻璃纤维 1384
玻璃纤维增强复合材料 1385
玻璃 1386
全地形车（沙滩车） 1387
疏散平台 1388
电缆槽 1389
通信箱盒 1390
电气绝缘部件 1391
纯苯 1392
柴油 1393
液化石油气 1394
海上油田服务 1395
石油化工原料 1396
石油蜡 1397
地下储气库 1398
氯丁橡胶 1399
异戊橡胶 1400
热塑性弹性体（TPE） 1401
重油 1402
液化石油气供应 1403
苯乙烯类热塑性弹性体（TPES） 1404
丁腈橡胶 1405
软件服务（SaaS） 1406
生物柴油 1407
精准营销 1408
石油炼制 1409
石油天然气勘探开采 1410
苯乙烯 1411
合成纤维 1412
转运服务 1413
快递加盟商 1414
集装箱制造 1415
快递 1416
镍矿石 1417
建筑工程 1418
商业建筑工程 1419
冶炼设备 1420
工业建筑工程 1421
经济作物种植 1422
农产品批发 1423
肉类屠宰加工 1424
精洗煤 1425
煤气供应 1426
蔬菜制品 1427
食品饮料零售 1428
鸡精 1429
罐头食品 1430
消毒剂 1431
婚纱摄影 1432
机器翻译 1433
云安全 1434
信息技术运维服务 1435
云计算 1436
信息科技应用服务 1437
医学影像信息系统（PACS） 1438
机架式服务器 1439
结构陶瓷 1440
燃料电池隔膜板 1441
陶瓷基复合材料 1442
光纤连接器 1443
电子陶瓷 1444
瓷体材料 1445
窄带滤光片 1446
电容器 1447
电阻 1448
热敏打印头 1449
被动元件 1450
电子浆料 1451
投融资中介服务 1452
电视剧制作 1453
造星及明星孵化 1454
网络影视 1455
原创音乐平台 1456
移动应用程序 1457
OTT业务 1458
IPTV 1459
电视购物 1460
视频广告 1461
互动营销 1462
网络自制 1463
文化艺术服务 1464
影视衍生品 1465
视频网站 1466
有线和卫星电视 1467
民航运输 1468
畜禽冻精及胚胎生产 1469
行业云 1470
数据管理 1471
信息技术产品经销 1472
塔式服务器 1473
Iaas 1474
IaaS 1475
军用飞机 1476
军用无人机 1477
航空装备 1478
火电机组及相关设备 1479
热力生产与供应 1480
化学制品 1481
手机显示屏模组 1482
柔性OLED屏幕 1483
红外截止滤光片 1484
金属结构件 1485
消费电子结构件 1486
数字电视接入设备 1487
电子设备技术服务 1488
电子设备维护服务 1489
玻璃添加剂 1490
非金属材料及制品 1491
电子焊接设备 1492
锂电池制片机 1493
锂电池辊压机 1494
锂电池叠片机 1495
锂电池化成柜 1496
全自动注液机 1497
锂电池分容柜 1498
锂电池分切设备 1499
自动化检测设备 1500
智能制造装备 1501
电池检测系统 1502
自动化装配设备 1503
智能仓储 1504
极片模切设备 1505
锂电池碾压设备 1506
智能装备制造与系统集成 1507
质押 1508
企业服务/投资融资对接平台 1509
乳制品 1510
兽用化学药品 1511
畜牧水产养殖机械 1512
居住房地产 1513
公寓 1514
建筑产品贸易 1515
工业物业管理 1516
房地产媒体社区平台 1517
邮轮客运 1518
五金配件 1519
门窗五金件 1520
门锁 1521
建筑五金 1522
轮胎 1523
半钢子午线轮胎 1524
车身附件 1525
全钢子午线轮胎 1526
离子型矿 1527
稀土永磁材料 1528
稀土储氢材料 1529
稀土催化材料 1530
稀土材料 1531
盐类 1532
进出口贸易 1533
配制酒 1534
铜矿石 1535
专业技术服务 1536
键合丝金属原料 1537
引线框架金属原料 1538
水泥 1539
石灰石 1540
水泥熟料 1541
砂石 1542
浮法玻璃 1543
厢式车 1544
航天飞机 1545
矿产品及建材批发 1546
婴幼儿配方奶粉 1547
奶牛养殖 1548
常温牛奶（液态奶） 1549
酸奶 1550
含乳饮料 1551
豆乳 1552
鲜牛奶 1553
成人奶粉 1554
奶酪 1555
婴幼儿羊奶粉 1556
调制乳粉 1557
冰淇淋 1558
核桃乳 1559
豆奶粉 1560
食用益生菌 1561
乳制品贸易 1562
2-羟基丙酸（乳酸）及其衍生物 1563
纸包装 1564
无菌包装 1565
BOPP薄膜 1566
锂离子电池隔膜 1567
包装材料 1568
包装纸 1569
民营银行 1570
制剂CMO 1571
商业化CMO 1572
化学试剂 1573
化学药CMO 1574
临床分析测试服务 1575
数据统计与分析 1576
航空发动机 1577
无人机用发动机 1578
军用红外 1579
蒸汽轮机 1580
航天装备 1581
电子和电工机械专用设备 1582
宏基站 1583
2-3-4-5G 1584
eMTC 1585
电信运营服务 1586
电信业务 1587
生物制药原料 1588
ACYW135群脑膜炎球菌多糖疫苗 1589
涤纶短纤 1590
工具钢 1591
轴承钢 1592
弹簧钢 1593
军工用钢 1594
齿轮钢 1595
钢铁材料 1596
特殊钢 1597
高温合金 1598
锯片锯条 1599
电梯广告 1600
户外广告 1601
户外广告媒介代理 1602
传媒 1603
广告营销 1604
轨道交通广告 1605
电视广告 1606
电影广告 1607
厨具卫具及日用杂品零售 1608
软件与互联网 1609
广告平台 1610
即时通讯类 1611
炊具 1612
营养煲 1613
保温杯 1614
刀具 1615
除螨仪 1616
家用电器 1617
橡塑制品贸易 1618
即时配送 1619
通讯设备经销 1620
B2C类电商 1621
电商代运营 1622
B2B类综合电商 1623
支付工具 1624
B2C玩具电商 1625
互联网数字阅读 1626
国内多方通信服务 1627
智能零售系统 1628
便利店 1629
化妆品批发 1630
B2C化妆品电商 1631
B2C奢侈品电商 1632
海淘、代购 1633
电竞游戏 1634
新零售 1635
B2C服装服饰电商 1636
O2O便利店 1637
网络直播营销 1638
传统家政平台 1639
C2C综合类电商 1640
B2C电子产品电商 1641
C2M、C2F类电商 1642
批发零售业 1643
零售代理商 1644
休闲卤制品 1645
肉脯类休闲食品 1646
休闲食品 1647
肉制类休闲食品 1648
便利货架 1649
DIY家具 1650
定制衣柜 1651
定制橱柜 1652
窗帘 1653
建筑墙纸 1654
刨花板 1655
纤维板 1656
衣柜 1657
橱柜 1658
卫浴电器 1659
木质门窗 1660
住宅装修装饰工程 1661
定制家居 1662
桌椅茶几 1663
木质门 1664
家具 1665
驱动IC 1666
光电晶体管 1667
晶体管 1668
电子设备及元器件经销 1669
微控制芯片 1670
集成电路增值分销 1671
电源管理芯片 1672
电子元器件B2B平台 1673
半导体设备贸易 1674
科研级基因检测服务 1675
生育健康检测 1676
生物基材料 1677
胶体金IVD 1678
基因类科研试剂 1679
独立医学实验室 1680
基因芯片 1681
组织芯片 1682
单细胞测序 1683
NGS微生物检测 1684
第二代基因测序（NGS） 1685
基因捕获 1686
CTC检测 1687
ctDNA检测 1688
司法基因检测 1689
基因检测设备及耗材 1690
宫颈癌检测（HPV检测） 1691
基因检测服务 1692
塑料手套 1693
丁腈手套 1694
养老护理服务 1695
乳胶制品 1696
康复治疗器械 1697
PVC手套 1698
医用一次性手套 1699
电极片 1700
康复教育设备 1701
个人护理用品 1702
病理诊断中心 1703
检验、检测、认证 1704
工业硅 1705
有机硅单体 1706
硅油 1707
三氯氢硅 1708
硅粉 1709
有机硅化合物 1710
借贷服务 1711
地坪漆 1712
混凝土外加剂 1713
防水涂料 1714
建筑防水材料 1715
自流平石膏 1716
建筑涂料 1717
沥青贸易 1718
毡 1719
岩棉板 1720
建筑维修维护 1721
保温装饰板 1722
压力触控芯片 1723
电子连接器 1724
通信终端设备用零件 1725
工业控制用电子连接器 1726
通讯电子连接器 1727
插座接插件 1728
长焦镜头 1729
潜望式长焦镜头 1730
消费电子连接线 1731
手机连接器 1732
精密线缆连接组件 1733
通讯连接器 1734
汽车连接器 1735
电声器件 1736
光学设备和仪器 1737
有轨电车整车 1738
城市轨道交通运输 1739
铁路设备 1740
有轨电车 1741
铁路车辆 1742
机车 1743
客运火车 1744
货运火车 1745
铁路机车配件 1746
动车组 1747
油气装备铸件 1748
轨道车辆电气设备 1749
实业投资 1750
屏蔽门窗 1751
空间钢结构 1752
水环境治理 1753
混凝土预制构件 1754
建筑工程设计 1755
混凝土桩 1756
钢筋混凝土排水管（RCP管） 1757
住宅房屋建筑工程 1758
公共建筑工程 1759
酒类分销商 1760
家务机器人 1761
个人、家用服务机器人 1762
工业互联网 1763
LCD屏幕 1764
笔记本电脑结构件 1765
来料加工 1766
运行内存芯片 1767
燃料电池动力系统 1768
工业地产租赁 1769
双层电路板 1770
智能电视 1771
黑色家电核心部件 1772
电视 1773
智能灯泡 1774
智能电视盒 1775
LCD电视 1776
医学影像设备 1777
半导体材料 1778
多晶硅 1779
生物滤池 1780
井下作业服务 1781
钻井完井服务 1782
油田技术服务 1783
石油天然气运输和储存 1784
原油船 1785
农村小额贷款 1786
舒芬太尼 1787
瑞芬太尼 1788
咪达唑仑 1789
麻醉药 1790
氢吗啡酮 1791
纳布啡 1792
安非他酮 1793
丙泊酚 1794
罗哌卡因 1795
小牛血去蛋白提取物 1796
氯化钾缓释片 1797
对乙酰氨基酚 1798
麻醉镇痛药 1799
泛昔洛韦 1800
蛋白激酶抑制剂 1801
丁螺环酮 1802
哌甲酯 1803
瑞马唑仑 1804
泻药及止泻药 1805
饲料级维生素 1806
类胡萝卜素 1807
维生素A 1808
食品级维生素 1809
聚苯硫醚 1810
维生素E原料药（VE） 1811
维生素A原料药（VA） 1812
柠檬醛 1813
丁二醇（BDO）深加工 1814
香料香精 1815
二硫化碳 1816
水果、坚果、饮料和香料作物的种植 1817
合成香料 1818
医药中间体 1819
天然香料 1820
大宗原料药 1821
维生素补充剂 1822
氨基酸 1823
凉味剂 1824
甲叉 1825
再保险 1826
保险销售 1827
石英矿 1828
平板玻璃（玻璃原片） 1829
建筑玻璃 1830
家电玻璃 1831
信息技术硬件与设备 1832
有机金属化学气相沉积MOCVD 1833
刻蚀设备 1834
精密洗净服务 1835
轨道交通信号系统 1836
列车控制系统 1837
国际/跨境物流 1838
堆存业务 1839
辅助生育医疗 1840
口腔专科医院 1841
口腔诊所 1842
别墅 1843
商业地产 1844
医药流通行业软件 1845
平台服务（PaaS） 1846
行业通用类SaaS 1847
房地产信息系统 1848
智能物流软件 1849
推广营销 1850
营销工具/营销软件 1851
企业支付 1852
记账工具 1853
税务类SAAS 1854
冷轧钢板 1855

In [25]:
# (产业链A, 上游, 产业链B)
edge_dict = dict()
counter = 0
for row in industries_df.iterrows():
    edge_key = ''
    ind_1 = row[1]['UDINDUSTRYNAME']
    ind_2 = row[1]['INDUSTRYNAME']
    rel = row[1]['POSITION']
    if rel == '上游':
        edge_key = str(node_dict.get(ind_2)) + '-' + str(node_dict.get(ind_1))
    else:
        edge_key = str(node_dict.get(ind_1)) + '-' + str(node_dict.get(ind_2))
    if edge_dict.get(edge_key) != None:
        continue
    else:
        edge_dict[edge_key] = counter
        counter += 1
print(len(edge_dict))

28388

In [ ]:
with open('/home/chenhaoran/FinancialTextAnalysis/CSI300_industry_graph/entity2id.txt', 'w') as f:
    f.write(str(len(node_dict)) + '\n')
    for (key, value) in node_dict.items():
        # print(key, value)
        f.write(str(key) + '\t' + str(value) + '\n')

In [ ]:
with open('/home/chenhaoran/FinancialTextAnalysis/CSI300_industry_graph/relation2id.txt', 'w') as f:
    f.write("1" + '\n')
    f.write('上游' + '\t0\n')

In [28]:
with open('/home/chenhaoran/FinancialTextAnalysis/CSI300_industry_graph/train2id.txt', 'w') as f:
    f.write(str(len(edge_dict)) + '\n')
    for key in edge_dict.keys():
        head, tail = key.split('-')
        f.write(head + '\t' + tail + '\t0\n')

## 构建产业名称到embedding的字典

In [1]:
import pickle
import json
import pandas as pd
import numpy as np

In [2]:
with open('/home/chenhaoran/GraphEmbedding/OpenKE/checkpoint/transh.embed.vec') as f:
    inds_embeddings = json.load(f)
inds_embeddings = inds_embeddings.get('ent_embeddings.weight')

In [4]:
len(inds_embeddings), len(inds_embeddings[0])

(6527, 200)

In [16]:
emb_dict = {}
with open('/home/chenhaoran/FinancialTextAnalysis/CSI300_industry_graph/entity2id.txt', 'r') as f:
    for l in f.readlines()[1:]:
        line = l.strip()
        name, idx = line.split('\t')
        emb_dict[name] = inds_embeddings[int(idx)]

In [18]:
'''
shape: 6527 x 200
{
    '智慧工厂': [],
    ...
}
'''
with open('/home/chenhaoran/FinancialTextAnalysis/coling2018/csi300_industry_graph/industry_embeddings.dict', 'w') as f:
    f.write(str(emb_dict))

In [3]:
with open('/home/chenhaoran/FinancialTextAnalysis/listed_companies_info.dump', 'rb') as f:
    listed_companies_info = pickle.load(f)
listed_companies_info

,Cuntrycd,Stkcd,Conme,Conme_en,Indcd,Indnme,Nindcd,Nindnme,Nnindcd,Nnindnme,...,Crcd,Statdt,Commnt,Markettype,PROVINCE,PROVINCECODE,CITY,CITYCODE,OWNERSHIPTYPE,OWNERSHIPTYPECODE
Stknme,,,,,,,,,,,,,,,,,,,,,
平安银行,10,000001,平安银行股份有限公司,"Ping An Bank Co., Ltd.",0001,金融,I01,银行业,J66,货币金融服务,...,NaN,2021-08-27,NaN,4.0,广东省,440000,深圳市,440300,私营企业,P0306
万科A,10,000002,万科企业股份有限公司,"China Vanke Co., Ltd.",0003,房地产,J,房地产业,K70,房地产业,...,NaN,2021-08-27,02202,4.0,广东省,440000,深圳市,440300,国营或国有控股,P0301
PT 金田A,10,000003,金田实业(集团)股份有限公司,"Gintian Industry (Group) Co., Ltd.",0004,综合,M,综合类,S90,综合,...,NaN,2002-06-14,NaN,4.0,广东省,440000,深圳市,440300,国营或国有控股,P0301
国华网安,10,000004,深圳国华网安科技股份有限公司,"Shenzhen Cau Technology Co., Ltd.",0002,公用事业,G87,计算机应用服务业,I65,软件和信息技术服务业,...,NaN,2021-08-27,NaN,4.0,广东省,440000,深圳市,440300,私营企业,P0306
ST 星源,10,000005,深圳世纪星源股份有限公司,Shenzhen Fountain Corporation,0002,公用事业,K99,其他社会服务业,N77,生态保护和环境治理业,...,NaN,2021-08-27,NaN,4.0,广东省,440000,深圳市,440300,中外合资,P0303
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
锦港B股,10,900952,锦州港股份有限公司,"Jinzhou Port Co., Ltd.",0002,公用事业,F07,水上运输业,G55,水上运输业,...,600190,2021-08-27,NaN,2.0,辽宁省,210000,锦州市,210700,国营或国有控股,P0301
凯马B,10,900953,恒天凯马股份有限公司,"Kama Co., Ltd.",0005,工业,C75,交通运输设备制造业,C36,汽车制造业,...,NaN,2021-08-27,NaN,2.0,上海市,310000,上海市,310000,国营或国有控股,P0301
*ST 海创B,10,900955,海航创新股份有限公司,"HNA Innovation Co., Ltd.",0003,房地产,J,房地产业,K70,房地产业,...,600555,2021-08-27,NaN,2.0,海南省,460000,三亚市,460200,中外合资,P0303
东贝B股,10,900956,黄石东贝电器股份有限公司,"Huangshi Dongbei Electrical Appliance Co., Ltd.",0005,工业,C71,普通机械制造业,C34,通用设备制造业,...,NaN,2020-11-23,NaN,2.0,湖北省,420000,黄石市,420200,国营或国有控股,P0301
凌云B股,10,900957,上海凌云实业发展股份有限公司,"Shanghai Lingyun Industries Development Co., Ltd.",0003,房地产,J,房地产业,K70,房地产业,...,NaN,2021-08-27,NaN,2.0,上海市,310000,上海市,310000,私营企业,P0306

In [19]:
code_to_name = listed_companies_info['Stkcd'].reset_index().rename(columns={'Stkcd': 'COMPANY_CODE'})
code_to_name

       Stknme COMPANY_CODE
0        平安银行       000001
1         万科A       000002
2      PT 金田A       000003
3        国华网安       000004
4       ST 星源       000005
...       ...          ...
4862     锦港B股       900952
4863      凯马B       900953
4864  *ST 海创B       900955
4865     东贝B股       900956
4866     凌云B股       900957

[4867 rows x 2 columns]

In [36]:
name_to_industries = industries_df.join(code_to_name.set_index('COMPANY_CODE'), on="COMPANY_CODE", lsuffix='_ind', rsuffix='_std', how='inner')
name_to_industries = name_to_industries[['Stknme', 'INDUSTRYNAME']].drop_duplicates()
name_to_industries

    Stknme INDUSTRYNAME
0     晶盛机电         智慧工厂
32    晶盛机电     机电设备安装劳务
78    晶盛机电       橡胶加工设备
105   晶盛机电          扩散炉
109   晶盛机电          单晶炉
..     ...          ...
367   君正集团           水泥
0     百润股份         食用香精
6     百润股份          鸡尾酒
15    百润股份         香料香精
39    百润股份        食品添加剂

[4018 rows x 2 columns]

In [38]:
name_to_industries_dict = {}
for row in name_to_industries.iterrows():
    stknme = row[1]['Stknme']
    indnme = row[1]['INDUSTRYNAME']
    ind_list = name_to_industries_dict.get(stknme)
    if ind_list:
        ind_list.append(indnme)
    else:
        name_to_industries_dict[stknme] = [indnme]
len(name_to_industries_dict)

297

In [39]:
'''
length: 297
[
    {'晶盛机电': ['智慧工厂', '机电设备安装劳务', '橡胶加工设备', '扩散炉', '单晶炉', '气动密封', '智能能源', '晶圆', '多晶炉', '自动化工程', '电池片生产设备', '三极管', 'LED衬底材料'] },
    ...
]
'''
with open('/home/chenhaoran/FinancialTextAnalysis/coling2018/csi300_industry_graph/name_to_industries.dict', 'w') as f:
    f.write(str(name_to_industries_dict))

## 测试industry encoder torch module

In [1]:
from turtle import forward
import torch
import torch.nn as nn
import torch.nn.functional as F
# from torch.autograd import Variable
from torch.nn import LSTM

In [2]:
def sequence_mask(lengths, max_len = None, device = 0):
	device = torch.device("cuda:%s" % device\
	 if torch.cuda.is_available() and device != -1 else "cpu")
	if not max_len:
		max_len = torch.max(lengths)
	#(1, max_len)
	range_matrix = torch.arange(0, max_len, 1, \
		dtype = torch.float, device = device).unsqueeze(0)
	#(batch_size, 1)
	lengths_expanded = lengths.float().unsqueeze(-1)
	return torch.lt(range_matrix, lengths_expanded).float()

def softmax_with_mask(score, mask = None, dim = -1):
	if mask is not None:
		score = score.masked_fill(mask == 0., -1e9)
	p_attn = F.softmax(score, dim = dim)
	return p_attn

In [3]:
class AttNet(nn.Module):
  """docstring for AttNet"""
  def __init__(self, config, input_dim):
    super(AttNet, self).__init__()
    self.config = config
    # self.affine = nn.Linear(input_dim, 1)
    self.w_q = nn.Linear(input_dim, input_dim, bias = False)
    self.w_f = nn.Linear(input_dim, input_dim, bias = True)

    self.affine = nn.Sequential(nn.Tanh(),\
     nn.Dropout(p = config.dropout), nn.Linear(input_dim, 1))

  #query(batch_size, 1, hidden_dim)
  #facts(batch_size, max_seqlen, hidden_dim)
  #fact_mask(batch_size, max_seqlen, 1)
  #return (batch_size, hidden_dim)
  def forward(self, facts, query = None, fact_mask = None):

    if query is not None:
      # max_seqlen = facts.size(1)
      # query = query.unsqueeze(1).repeat(1, max_seqlen, 1)
      # #(batch_size, max_seqlen, hidden_dim * 2)
      # output = torch.cat([query, facts], dim = -1)
      # print("baseline.py line 33, AttNet query.shape: ", query.shape, " facts.shape: ", facts.shape)
      output = self.w_q(query.unsqueeze(1)) + self.w_f(facts)
    else:
      output = facts

    #(batch_size, max_seqlen, 1)
    weights = self.affine(output)
    norm_weights = softmax_with_mask(weights, mask = fact_mask, dim = 1)

    return torch.sum(norm_weights * facts, dim = 1)


class Attention(nn.Module):

  def __init__(self, config, input_dim):
    super(Attention, self).__init__()

    self.att = nn.Sequential(\
      nn.Linear(input_dim, input_dim), nn.Tanh(),\
      nn.Linear(input_dim, 1, bias = False))
    self.dropout = nn.Dropout(p = config.dropout)

  #facts(batch_size, max_seq_len, input_dim)
  #fact_mask(batch_size, max_seq_len, 1)
  #return(batch_size, embed_dim)
  def forward(self, facts, fact_mask = None, hard = False, tau = 1, dim = -1):

    #(batch_size, max_seq_len, 1)
    scores = self.att(facts)

    if hard:
      scores = scores.squeeze(-1)
      if fact_mask is not None:
        p_attn = gumbel_softmax(scores, fact_mask.squeeze(-1), tau = tau)
      else:
        p_attn = gumbel_softmax(scores, None, tau = tau)
      return torch.sum(p_attn.unsqueeze(-1) * facts, dim = dim)

    else:
      p_attn = softmax_with_mask(scores, fact_mask, dim = dim)
      p_attn = self.dropout(p_attn)
      return torch.sum(p_attn * facts, dim = dim)

#sequential representation
class SequentialRepr(nn.Module):
  def __init__(self, config, input_dim = 100, mode = 'cnn'):
    super(SequentialRepr, self).__init__()

    self.mode = mode
    self.config = config
    self.input_dim = input_dim

    self.c0_initer = nn.Linear(input_dim, config.hidden_dim)
  
    if mode == 'cnn':
      ks = [int(c) for c in config.kernel_sizes.split(',')]
      self.encoder = CNNText(config, ks)

    elif mode.startswith("gru"):
      self.encoder = nn.GRU(input_size = input_dim, batch_first = True, \
        hidden_size = config.hidden_dim,  bidirectional = True, \
        num_layers = 1)

    elif mode.startswith('lstm'):
      self.encoder = nn.LSTM(input_size = input_dim, batch_first = True, \
        hidden_size = config.hidden_dim,  bidirectional = True, \
        num_layers = 1)

    if mode.endswith('att'):
      self.att = Attention(config, config.hidden_dim)


  # text_embed(batch_size, seqlen, embed_dim)
  # mask(batch_size, seqlen, 1)
  def forward(self, text_embed, init = None, mask = None):

    hiddens, output = None, None
    if self.mode.startswith("gru") or self.mode.startswith('lstm'):

      if init is not None:

        batch_size = text_embed.size(0) // init.size(0)
        init = c0 = init.unsqueeze(0).repeat(2, batch_size, 1)

        if self.mode.startswith("lstm"):
          c0 = self.c0_initer(c0) if self.config.bert == "true" else c0
          h0 = torch.zeros_like(c0)
          init = (h0, c0)
          # print(">>>>>", text_embed.shape, h0.shape, c0.shape)
      hiddens, output = self.encoder(text_embed, init)
      hsize = hiddens.size()
      hiddens = hiddens.view(*hsize[:-1], 2, -1)
      hiddens = hiddens.mean(dim = -2, keepdim = False)
      # print("baseline.py line 126 hiddens.shape==>", hiddens.shape)
      if self.mode.endswith('avg'):
        if mask is not None:
          output = torch.sum(hiddens * mask, dim = 1) / (torch.sum(mask, dim = 1) + 1e-8)
        else:
          output = torch.mean(hiddens, dim = 1, keepdim = False)
      elif self.mode.endswith('att'):
        output = self.att(hiddens, mask, dim = 1)
      # print("baseline.py line 134 output.shape==>", output.shape)
    elif self.mode == 'cnn':
      output = self.encoder(text_embed)

    else:
      raise Exception('mode %s not defined!' % self.mode)
    return hiddens, output

In [4]:
class IndustryEncoder(nn.Module):
  def __init__(self, config, dim = 128,) -> None:
    super(IndustryEncoder, self).__init__()
    self.ind_dim = dim
    self.target_to_inds = config.target_to_inds
    self.inds_embs = config.inds_embs
    self.seq_encoder = SequentialRepr(config, input_dim = config.embed_dim, mode = 'lstm')
    self.inds_attn = AttNet(config, input_dim=128)
    self.linear = nn.Linear(config.embed_dim, self.ind_dim)

  def forward(self, target, lead):
    inds = self.target_to_inds
    _, lead_reprs = self.seq_encoder(lead, )
    query = self.linear(lead_reprs)
    industry_reprs = self.inds_attn()
    return